/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTS_B.view;
import UTS_B.controller.*;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author TUF Gaming
 */
public class PesananForm extends javax.swing.JFrame {

    /**
     * Creates new form PesananForm
     */
    PesananController controller;
    public PesananForm() {
        initComponents();
        controller = new PesananController(this);
        controller.bersihForm();
        controller.tampil();
    }
    
    public javax.swing.JTextField getTxtKodePesanan(){
        return txtKodePesanan;
    }
    
    public javax.swing.JTextField getTxtNamaPemesan(){
        return txtNamaPemesan;
    }
    
    public javax.swing.JTextField getTxtTanggalPesan(){
        return txtTanggalPesan;
    }
    
    public javax.swing.JTextField getTxtHarga(){
        return txtHarga;
    }
    
    public javax.swing.JTextField getTxtOngkosKirim(){
        return txtOngkosKirim;
    }
    
    public javax.swing.JTextField getTxtDiskon(){
        return txtDiskon;
    }
    
    public javax.swing.JTable getTblPesanan(){
        return tblPesanan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodePesanan = new javax.swing.JTextField();
        txtNamaPemesan = new javax.swing.JTextField();
        txtTanggalPesan = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtOngkosKirim = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Program UTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 90, 30);

        jLabel2.setText("Kode Pesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 140, 20);

        jLabel3.setText("Nama Pemesan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 140, 18);

        jLabel4.setText("Tanggal Pesan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 150, 18);

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 130, 18);

        jLabel6.setText("Ongkos Kirim");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 130, 18);

        jLabel7.setText("Diskon");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 230, 130, 18);

        txtKodePesanan.setText("jTextField1");
        getContentPane().add(txtKodePesanan);
        txtKodePesanan.setBounds(180, 70, 400, 30);

        txtNamaPemesan.setText("jTextField2");
        getContentPane().add(txtNamaPemesan);
        txtNamaPemesan.setBounds(180, 100, 400, 30);

        txtTanggalPesan.setText("jTextField3");
        txtTanggalPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalPesanActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggalPesan);
        txtTanggalPesan.setBounds(180, 130, 400, 30);

        txtHarga.setText("jTextField4");
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtHarga);
        txtHarga.setBounds(180, 160, 400, 30);

        txtOngkosKirim.setText("jTextField5");
        getContentPane().add(txtOngkosKirim);
        txtOngkosKirim.setBounds(180, 190, 400, 30);

        txtDiskon.setText("jTextField6");
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(180, 220, 400, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(100, 280, 72, 24);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(260, 280, 73, 24);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(410, 280, 72, 24);

        jButton4.setText("Cancel");
        getContentPane().add(jButton4);
        jButton4.setBounds(550, 280, 72, 24);

        tblPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pesanan", "Nama ", "Tgl Pesan", "Harga", "Ongkir", "Diskon", "Total"
            }
        ));
        tblPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesanan);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 330, 620, 280);

        setSize(new java.awt.Dimension(735, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtTanggalPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalPesanActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.savePesanan();
        controller.tampil();
        controller.bersihForm(); 
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.updatePesanan();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.tampil();
        controller.bersihForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesananMouseClicked
        // TODO add your handling code here:
        controller.getPesanan();
    }//GEN-LAST:event_tblPesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesananForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesananForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesanan;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKodePesanan;
    private javax.swing.JTextField txtNamaPemesan;
    private javax.swing.JTextField txtOngkosKirim;
    private javax.swing.JTextField txtTanggalPesan;
    // End of variables declaration//GEN-END:variables
}
